- name: create install dir
  file:
    path: "{{ install_base }}"
    state: directory

- name: create grafana group
  group:
    name: grafana
    state: present

- name: create grafana user
  user:
    name: grafana
    group: grafana
    createhome: false

- name: fetch grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-{{ ver }}.linux-amd64.tar.gz
    dest: "{{ tarball_loc }}"
  register: fetch

- name: extract grafana
  unarchive:
    src: "{{ tarball_loc }}"
    dest: "{{ install_base }}"
    copy: no
    owner: grafana
    group: grafana
  when: fetch.changed
  notify: restart grafana

- name: create dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: grafana
  with_items:
    - "{{ log_dir }}"
    - "{{ data_dir }}"
    - "{{ data_dir}}/plugins"
    - "{{ config_dir}}"

- name: grafana service file
  template:
    src=grafana.service.j2 dest=/etc/systemd/system/{{ service_name }}.service
  notify:
    - reload systemd
    - restart grafana

- name: grafana config
  template: src=grafana.ini.j2 dest={{ config_dir }}/grafana.ini owner=grafana
  notify: restart grafana

- name: start grafana
  service: name=grafana state=started enabled=yes
